name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          make deps
          mkdir -p dist

          # Build for macOS (amd64 and arm64)
          GOOS=darwin GOARCH=amd64 go build -o dist/psjungle-darwin-amd64 ./cmd/psjungle
          GOOS=darwin GOARCH=arm64 go build -o dist/psjungle-darwin-arm64 ./cmd/psjungle

          # Build for Linux (amd64 and arm64)
          GOOS=linux GOARCH=amd64 go build -o dist/psjungle-linux-amd64 ./cmd/psjungle
          GOOS=linux GOARCH=arm64 go build -o dist/psjungle-linux-arm64 ./cmd/psjungle

      - name: Create archives
        run: |
          cd dist

          # Create tar.gz archives
          tar -czvf psjungle-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz psjungle-darwin-amd64
          tar -czvf psjungle-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz psjungle-darwin-arm64
          tar -czvf psjungle-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz psjungle-linux-amd64
          tar -czvf psjungle-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz psjungle-linux-arm64

          # Create zip archives
          zip psjungle-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.zip psjungle-darwin-amd64
          zip psjungle-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.zip psjungle-darwin-arm64

          # Remove binaries
          rm psjungle-darwin-amd64 psjungle-darwin-arm64 psjungle-linux-amd64 psjungle-linux-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
          draft: false
          prerelease: false